name: Actions workflow
on: [push]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Majid

